### PR TITLE
add support for for custom ini section

### PR DESCRIPTION
**Pull request by oba11**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] RuboCop passes

- [ ] Existing tests pass 

#### Purpose
Add support for custom sections in the inifile

#### Known Compatablity Issues
None

### CODE REVIEW

**Comment by majormoses** [comment]
@oba11 can you please expand on the use case a bit?

**Comment by oba11** [comment]
@majormoses Thanks for taking a look at the PR.
For quite a while, we have been using the inifile instead of arguments (which exposes credentials) or client config variable but this works for a single database client config.
Lets say you want to connect to multiple databases with multiple client configs in the inifile, the current way of passing the inifile wont work unless the inifile is splitted into multiple files with and the section name changed to `client`.

The PR doesn't break backward compatibility while also ensuring that multiple mysql client config sections can be read from a single inifile.

Btw actually introduced the use of inifile a while back https://github.com/sensu/sensu-community-plugins/pull/617

**Comment by majormoses** [comment]
> For quite a while, we have been using the inifile instead of arguments (which exposes credentials) or client config variable but this works for a single database client config.

That's great to hear, unfortunately far too many people just store these in plain text and do not use token substitution and therefore expose creds to at best the process table or worst an external system like pagerduty, logs, etc.

> Lets say you want to connect to multiple databases with multiple client configs in the inifile, the current way of passing the inifile wont work unless the inifile is splitted into multiple files with and the section name changed to `client`.

Makes total sense, I guess I would probably have just split them out to multiple files but it's probably easier to have a single file. If you are not gonna restrict say which machines should be checking for which databases different files would make more sense.

 > The PR doesn't break backward compatibility while also ensuring that multiple mysql client config sections can be read from a single inifile.

Yup I noticed and appreciated that, Great Job!

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-mysql/versions/2.2.0

**Comment by oba11** [comment]
Thanks alot @majormoses :+1:

**Pull request merged**
