### PR TITLE
change '-s' for socket to -S

### PR DESCRIPTION
**Pull request by 2autunni**
## Pull Request Checklist

**Is this in reference to an existing issue?**
issue #61 
#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

**Comment by 2autunni** [comment]
@majormoses  excuse me for this PR without changelog.

**Comment by majormoses** [comment]
No problem.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-mysql/versions/2.1.2

**Pull request merged**
