### PR TITLE
Replace mysql gem with mysql2 gem in check-mysql-replication-status

### PR DESCRIPTION
**Pull request by dcharleston**

### CODE REVIEW

**Comment by SegFaultAX** [comment]
Unfortunately it looks like this plugin is now broken because of its transitive dependency on `json` via [sensu-plugin](https://github.com/sensu-plugins/sensu-plugin/blob/master/sensu-plugin.gemspec#L18) which, [as of July 1](https://rubygems.org/gems/json) has a 2.x version that breaks compatibility with Ruby 1.9.x. There is an [open issue](https://github.com/sensu-plugins/sensu-plugin/pull/138) for strictly pinning the json dependency to something more specific, but as of this writing it's not merged.

**Comment by insom** [comment]
Hi,

Can I ask what the reason for upgrading to the `mysql2` gem is? I only ask because I'm looking at going in the other direction, and requiring only `ruby-mysql` instead of the full `mysql` gem - because at $WORK they don't install development packages for things like MySQL on production machines.

**Comment by sstarcher** [comment]
@insom mysql gem is pretty much deprecated.  The main prefered options are mysql2 gem or ruby-mysql gem.  A few checks in this repo already use mysql2 gem and it is much faster.

@sensu-plugins/commit-bit opinions on the direction of mysql2 vs ruby-mysql.  It certainly would be good to solidify on one gem since we currently use 2 separate gems, but I don't believe we use ruby-mysql at all.

**Comment by insom** [comment]
I see. I agree that the `mysql2` gem is much faster. `metrics-mysql-graphite.rb` is the only plugin which requires `mysql2` as of 2dfa38dbf (before this commit was merged) - the others work fine in an environment with only `ruby-mysql` installed.

I'm in the process of porting the metric plugin down to being compatible with `ruby-mysql` and will open a PR when I'm done. After that, just updating the gemspec should be enough. I understand if the project feels that the speed of the `mysql2` trumps the portability of the `ruby-mysql` gem though. Just my ¢2.

**Comment by sstarcher** [comment]
I can't speak for anyone else, but I would be fine with just ruby-mysql.  It would allow us to have one less dependency.

**Comment by eheydrick** [comment]
I'm a fan of fewer dependencies as well. `mysql2` looks like a more active project than `ruby-mysql`. But if `ruby-mysql` works and the performance is decent I'm fine with moving to it.

**Pull request merged**
