### PR TITLE
Ruby mysql

### PR DESCRIPTION
**Pull request by insom**
## Pull Request Checklist

This is in reference to the comments on #18 (though I suppose #12 / #13 are also relevant).

#### General

- [X] RuboCop passes

The code I've touched passes, though there were pre-existing failures.

#### Purpose

While the `mysql` gem is considered deprecated, the `ruby-mysql` gem has had recent updates (okay, not a lot of them) and doesn't require a working C build environment on the Sensu client.

My commits are relative to 2dfa38dbf1 - which is where the `mysql` to `mysql2` conversion starts. If you didn't want to rewrite history, commits after this point could be reverted, or I can include commits to reverse those changes, if that would leave the history looking cleaner.

I understand if the community reckons that `mysql2` is the way to go, though I will probably end up maintaining my fork indefinitely if that's the case.

#### Known Compatiblity Issues

None, I've tested each plugin in a gem environment without `mysql` and `mysql2` installed.

### CODE REVIEW

**Comment by sstarcher** [comment]
Do all current is ruby-mysql api compatible with the mysql gem?

**Comment by sstarcher** [comment]
@dcharleston also added mysql2 for check-mysql-replication-status.rb

**Comment by insom** [comment]
@sstarcher well if we add the `mysql2` gem for that check to the gemspec, the whole gem will still fail to install unless you have a compiler and a ruby-dev(el) package installed. Reverting 2d740ab 9bb5fc and 8a75802 (i.e. rewinding the code back to 2dfa38d ) would remove the `mysql2` upgrades of the `check-mysql-connections` and `check-mysql-replication-status` checks - the originals worked with `ruby-mysql`

**Comment by sstarcher** [comment]
@insom manually merged into master along with the reversion of the other commits.

**Pull request closed without merging**
