### PR TITLE
release version 0.1.0

### LINKED ISSUE #14: check-mysql-threads.rb not installed with gem
```
[/opt/sensu/embedded/bin]# ls -la | grep check-mysql
-rwxr-xr-x. 1 root root    533 Jun 14 21:22 check-mysql-alive.rb
-rwxr-xr-x. 1 root root    539 Jun 14 21:22 check-mysql-connections.rb
-rwxr-xr-x. 1 root root    532 Jun 14 21:22 check-mysql-disk.rb
-rwxr-xr-x. 1 root root    539 Jun 14 21:22 check-mysql-innodb-lock.rb
-rwxr-xr-x. 1 root root    546 Jun 14 21:22 check-mysql-replication-status.rb

[/opt/sensu/embedded/bin]# ./gem list | grep sensu-plugins-mysql
sensu-plugins-mysql (0.0.4)

[/opt/sensu/embedded/bin]# ls /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-mysql-0.0.4/bin/
check-cloudwatch-mysql-sensu.rb    check-mysql-connections.rb         check-mysql-innodb-lock.rb         metrics-mysql-graphite.rb          mysql-metrics.sql
check-mysql-alive.rb               check-mysql-disk.rb                check-mysql-replication-status.rb  metrics-mysql.rb
```

Is there a new release coming?

### PR DESCRIPTION
**Pull request by cwjohnston**
## Pull Request Checklist

Closes #14 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Publish unreleased changes already merged to master

#### Known Compatablity Issues

None known

### CODE REVIEW

**Comment by cwjohnston** [comment]
Looks like 928e57ac has changed `required_ruby_version` to 2.1.0

**Comment by cwjohnston** [comment]
This PR needs to change to bump version to 1.0.0 because of the ruby change.

@sstarcher is there a reason we can't support ruby 2.0.0 as we've been doing with other plugin gems when removing 1.9.3?

**Comment by sstarcher** [comment]
@cwjohnston you are correct that should've been 2.0.0 and not 2.1

**Comment by DazWorrall** [comment]
Is there anything we can do to help get a new release baked?

**Pull request closed without merging**
